.TH "src/mlpack Directory Reference" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBmethods\fP"
.br
.ti -1c
.RI "directory \fBtests\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcore\&.hpp\fP"
.br
.ti -1c
.RI "file \fBprereqs\&.hpp\fP"
.br
.RI "\fIThe core includes that mlpack expects; standard C++ includes and Armadillo\&. \fP"
.in -1c
