.TH "src/mlpack/core/data Directory Reference" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/data Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBload\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnormalize_labels\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsave\&.hpp\fP"
.br
.in -1c
