.TH "src/mlpack/methods/naive_bayes Directory Reference" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/naive_bayes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBnaive_bayes_classifier\&.hpp\fP"
.br
.in -1c
