.TH "src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::tree::CoverTree< MetricType, RootPointPolicy, StatisticType >::DualTreeTraverser< RuleType >\fP"
.br
.RI "\fIA dual-tree cover tree traverser; see dual_tree_traverser\&.hpp\&. \fP"
.ti -1c
.RI "struct \fBmlpack::tree::CoverTree< MetricType, RootPointPolicy, StatisticType >::DualTreeTraverser< RuleType >::DualCoverTreeMapEntry\fP"
.br
.RI "\fIStruct used for traversal\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI "\fBmlpack::tree\fP"
.br
.RI "\fITrees and tree-building procedures\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
