.TH "mlpack::gmm::DiagonalConstraint" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::gmm::DiagonalConstraint \- 
.PP
Force a covariance matrix to be diagonal\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBApplyConstraint\fP (arma::mat &covariance)"
.br
.RI "\fIForce a covariance matrix to be diagonal\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Force a covariance matrix to be diagonal\&. 
.PP
Definition at line 25 of file diagonal_constraint\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void mlpack::gmm::DiagonalConstraint::ApplyConstraint (arma::mat &covariance)\fC [inline]\fP, \fC [static]\fP"

.PP
Force a covariance matrix to be diagonal\&. 
.PP
Definition at line 29 of file diagonal_constraint\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
