.TH "mlpack::tree::BinarySpaceTree< BoundType, StatisticType, MatType, SplitType >::SingleTreeTraverser< RuleType >" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::BinarySpaceTree< BoundType, StatisticType, MatType, SplitType >::SingleTreeTraverser< RuleType > \- 
.PP
A single-tree traverser for binary space trees; see single_tree_traverser\&.hpp for implementation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleTreeTraverser\fP (RuleType &\fBrule\fP)"
.br
.RI "\fIInstantiate the single tree traverser with the given rule set\&. \fP"
.ti -1c
.RI "size_t \fBNumPrunes\fP () const "
.br
.RI "\fIGet the number of prunes\&. \fP"
.ti -1c
.RI "size_t & \fBNumPrunes\fP ()"
.br
.RI "\fIModify the number of prunes\&. \fP"
.ti -1c
.RI "void \fBTraverse\fP (const size_t queryIndex, \fBBinarySpaceTree\fP &referenceNode)"
.br
.RI "\fITraverse the tree with the given point\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "size_t \fBnumPrunes\fP"
.br
.RI "\fIThe number of nodes which have been pruned during traversal\&. \fP"
.ti -1c
.RI "RuleType & \fBrule\fP"
.br
.RI "\fIReference to the rules with which the tree will be traversed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BoundType, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = MeanSplit<BoundType, MatType>>template<typename RuleType>class mlpack::tree::BinarySpaceTree< BoundType, StatisticType, MatType, SplitType >::SingleTreeTraverser< RuleType >"
A single-tree traverser for binary space trees; see single_tree_traverser\&.hpp for implementation\&. 


.PP
Definition at line 91 of file binary_space_tree\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename BoundType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, typename SplitType  = MeanSplit<BoundType, MatType>> template<typename RuleType > \fBmlpack::tree::BinarySpaceTree\fP< BoundType, StatisticType, MatType, SplitType >::\fBSingleTreeTraverser\fP< RuleType >::\fBSingleTreeTraverser\fP (RuleType &rule)"

.PP
Instantiate the single tree traverser with the given rule set\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename BoundType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, typename SplitType  = MeanSplit<BoundType, MatType>> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< BoundType, StatisticType, MatType, SplitType >::\fBSingleTreeTraverser\fP< RuleType >::NumPrunes () const\fC [inline]\fP"

.PP
Get the number of prunes\&. 
.PP
Definition at line 50 of file single_tree_traverser\&.hpp\&.
.SS "template<typename BoundType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, typename SplitType  = MeanSplit<BoundType, MatType>> template<typename RuleType > size_t& \fBmlpack::tree::BinarySpaceTree\fP< BoundType, StatisticType, MatType, SplitType >::\fBSingleTreeTraverser\fP< RuleType >::NumPrunes ()\fC [inline]\fP"

.PP
Modify the number of prunes\&. 
.PP
Definition at line 52 of file single_tree_traverser\&.hpp\&.
.SS "template<typename BoundType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, typename SplitType  = MeanSplit<BoundType, MatType>> template<typename RuleType > void \fBmlpack::tree::BinarySpaceTree\fP< BoundType, StatisticType, MatType, SplitType >::\fBSingleTreeTraverser\fP< RuleType >::Traverse (const size_tqueryIndex, \fBBinarySpaceTree\fP &referenceNode)"

.PP
Traverse the tree with the given point\&. 
.PP
\fBParameters:\fP
.RS 4
\fIqueryIndex\fP The index of the point in the query set which is being used as the query point\&. 
.br
\fIreferenceNode\fP The tree node to be traversed\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<typename BoundType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, typename SplitType  = MeanSplit<BoundType, MatType>> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< BoundType, StatisticType, MatType, SplitType >::\fBSingleTreeTraverser\fP< RuleType >::numPrunes\fC [private]\fP"

.PP
The number of nodes which have been pruned during traversal\&. 
.PP
Definition at line 59 of file single_tree_traverser\&.hpp\&.
.SS "template<typename BoundType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, typename SplitType  = MeanSplit<BoundType, MatType>> template<typename RuleType > RuleType& \fBmlpack::tree::BinarySpaceTree\fP< BoundType, StatisticType, MatType, SplitType >::\fBSingleTreeTraverser\fP< RuleType >::rule\fC [private]\fP"

.PP
Reference to the rules with which the tree will be traversed\&. 
.PP
Definition at line 56 of file single_tree_traverser\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
