.TH "mlpack::amf::RandomInitialization" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::amf::RandomInitialization \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomInitialization\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename MatType > static void \fBInitialize\fP (const MatType &V, const size_t r, arma::mat &W, arma::mat &H)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file random_init\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::amf::RandomInitialization::RandomInitialization ()\fC [inline]\fP"

.PP
Definition at line 27 of file random_init\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename MatType > static void mlpack::amf::RandomInitialization::Initialize (const MatType &V, const size_tr, arma::mat &W, arma::mat &H)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 30 of file random_init\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
