.TH "mlpack::cf" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::cf \- 
.PP
Collaborative filtering\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCF\fP"
.br
.RI "\fIThis class implements Collaborative Filtering (\fBCF\fP)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collaborative filtering\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
