.TH "mlpack::kernel::KernelTraits< LaplacianKernel >" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::kernel::KernelTraits< LaplacianKernel > \- 
.PP
Kernel traits of the Laplacian kernel\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBIsNormalized\fP = true"
.br
.RI "\fIThe Laplacian kernel is normalized: K(x, x) = 1 for all x\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>class mlpack::kernel::KernelTraits< LaplacianKernel >"
Kernel traits of the Laplacian kernel\&. 
.PP
Definition at line 103 of file laplacian_kernel\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool \fBmlpack::kernel::KernelTraits\fP< \fBLaplacianKernel\fP >::IsNormalized = true\fC [static]\fP"

.PP
The Laplacian kernel is normalized: K(x, x) = 1 for all x\&. 
.PP
Definition at line 107 of file laplacian_kernel\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
