.TH "mlpack::nn" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::nn \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSparseAutoencoder\fP"
.br
.RI "\fIA sparse autoencoder is a neural network whose aim to learn compressed representations of the data, typically for dimensionality reduction, with a constraint on the activity of the neurons in the network\&. \fP"
.ti -1c
.RI "class \fBSparseAutoencoderFunction\fP"
.br
.RI "\fIThis is a class for the sparse autoencoder objective function\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
