.TH "mlpack::perceptron::RandomInitialization" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::perceptron::RandomInitialization \- 
.PP
This class is used to initialize weights for the weightVectors matrix in a random manner\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomInitialization\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP (arma::mat &W, const size_t row, const size_t col)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to initialize weights for the weightVectors matrix in a random manner\&. 
.PP
Definition at line 26 of file random_init\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::perceptron::RandomInitialization::RandomInitialization ()\fC [inline]\fP"

.PP
Definition at line 29 of file random_init\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void mlpack::perceptron::RandomInitialization::Initialize (arma::mat &W, const size_trow, const size_tcol)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 31 of file random_init\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
