.TH "mlpack::svd" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::svd \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQUIC_SVD\fP"
.br
.ti -1c
.RI "class \fBRegularizedSVD\fP"
.br
.ti -1c
.RI "class \fBRegularizedSVDFunction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
