.TH "mlpack::bound" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::bound \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBallBound\fP"
.br
.RI "\fIBall bound encloses a set of points at a specific distance (radius) from a specific point (center)\&. \fP"
.ti -1c
.RI "class \fBHRectBound\fP"
.br
.RI "\fIHyper-rectangle bound for an L-metric\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
