.TH "mlpack::fastmks" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::fastmks \- 
.PP
Fast max-kernel search\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFastMKS\fP"
.br
.RI "\fIAn implementation of fast exact max-kernel search\&. \fP"
.ti -1c
.RI "class \fBFastMKSRules\fP"
.br
.RI "\fIThe base case and pruning rules for \fBFastMKS\fP (fast max-kernel search)\&. \fP"
.ti -1c
.RI "class \fBFastMKSStat\fP"
.br
.RI "\fIThe statistic used in trees with \fBFastMKS\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fast max-kernel search\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
