.TH "mlpack::kernel::KernelTraits< EpanechnikovKernel >" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::kernel::KernelTraits< EpanechnikovKernel > \- 
.PP
Kernel traits for the Epanechnikov kernel\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBIsNormalized\fP = true"
.br
.RI "\fIThe Epanechnikov kernel is normalized: K(x, x) = 1 for all x\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>class mlpack::kernel::KernelTraits< EpanechnikovKernel >"
Kernel traits for the Epanechnikov kernel\&. 
.PP
Definition at line 92 of file epanechnikov_kernel\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool \fBmlpack::kernel::KernelTraits\fP< \fBEpanechnikovKernel\fP >::IsNormalized = true\fC [static]\fP"

.PP
The Epanechnikov kernel is normalized: K(x, x) = 1 for all x\&. 
.PP
Definition at line 96 of file epanechnikov_kernel\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
