.TH "mlpack::range" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::range \- 
.PP
Range-search routines\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRangeSearch\fP"
.br
.RI "\fIThe \fBRangeSearch\fP class is a template class for performing range searches\&. \fP"
.ti -1c
.RI "class \fBRangeSearchRules\fP"
.br
.ti -1c
.RI "class \fBRangeSearchStat\fP"
.br
.RI "\fIStatistic class for \fBRangeSearch\fP, to be set to the StatisticType of the tree type that range search is being performed with\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Range-search routines\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
