.TH "src/mlpack/tests/old_boost_test_definitions.hpp" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/tests/old_boost_test_definitions.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOOST_REQUIRE_GE\fP(L, R)   BOOST_REQUIRE_EQUAL( (L >= R), true )"
.br
.ti -1c
.RI "#define \fBBOOST_REQUIRE_GT\fP(L, R)   BOOST_REQUIRE_EQUAL( (L > R), true )"
.br
.ti -1c
.RI "#define \fBBOOST_REQUIRE_LE\fP(L, R)   BOOST_REQUIRE_EQUAL( (L <= R), true )"
.br
.ti -1c
.RI "#define \fBBOOST_REQUIRE_LT\fP(L, R)   BOOST_REQUIRE_EQUAL( (L < R), true )"
.br
.ti -1c
.RI "#define \fBBOOST_REQUIRE_NE\fP(L, R)   BOOST_REQUIRE_EQUAL( (L != R), true )"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Ryan Curtin
.RE
.PP
Ancient Boost\&.Test versions don't act how we expect\&. This file includes the things we need to fix that\&.
.PP
This file is part of mlpack 1\&.0\&.12\&.
.PP
mlpack is free software; you may redstribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBold_boost_test_definitions\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOOST_REQUIRE_GE(L, R)   BOOST_REQUIRE_EQUAL( (L >= R), true )"

.PP
Definition at line 28 of file old_boost_test_definitions\&.hpp\&.
.SS "#define BOOST_REQUIRE_GT(L, R)   BOOST_REQUIRE_EQUAL( (L > R), true )"

.PP
Definition at line 40 of file old_boost_test_definitions\&.hpp\&.
.SS "#define BOOST_REQUIRE_LE(L, R)   BOOST_REQUIRE_EQUAL( (L <= R), true )"

.PP
Definition at line 34 of file old_boost_test_definitions\&.hpp\&.
.SS "#define BOOST_REQUIRE_LT(L, R)   BOOST_REQUIRE_EQUAL( (L < R), true )"

.PP
Definition at line 37 of file old_boost_test_definitions\&.hpp\&.
.SS "#define BOOST_REQUIRE_NE(L, R)   BOOST_REQUIRE_EQUAL( (L != R), true )"

.PP
Definition at line 31 of file old_boost_test_definitions\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
