.TH "src/mlpack/prereqs.hpp" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/prereqs.hpp \- 
.PP
The core includes that mlpack expects; standard C++ includes and Armadillo\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.ti -1c
.RI "#define \fBforce_inline\fP"
.br
.ti -1c
.RI "#define \fBM_PI\fP   3\&.141592653589793238462643383279"
.br
.in -1c
.SH "Detailed Description"
.PP 
The core includes that mlpack expects; standard C++ includes and Armadillo\&. 

This file is part of mlpack 1\&.0\&.12\&.
.PP
mlpack is free software; you may redstribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBprereqs\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _USE_MATH_DEFINES"

.PP
Definition at line 34 of file prereqs\&.hpp\&.
.SS "#define force_inline"

.PP
Definition at line 46 of file prereqs\&.hpp\&.
.SS "#define M_PI   3\&.141592653589793238462643383279"

.PP
Definition at line 42 of file prereqs\&.hpp\&.
.PP
Referenced by mlpack::kernel::SphericalKernel::Normalizer(), mlpack::kernel::GaussianKernel::Normalizer(), and mlpack::gmm::phi()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
