.TH "src/mlpack/methods/rann/ra_typedef.hpp" 3 "Sat Mar 14 2015" "Version 1.0.12" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/rann/ra_typedef.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI "\fBmlpack::neighbor\fP"
.br
.RI "\fINeighbor-search routines\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBRASearch\fP
.br
< FurthestNeighborSort > \fBmlpack::neighbor::AllkRAFN\fP"
.br
.RI "\fIThe AllkRAFN class is the all-k-rank-approximate-farthest-neighbors method\&. \fP"
.ti -1c
.RI "typedef \fBRASearch\fP \fBmlpack::neighbor::AllkRANN\fP"
.br
.RI "\fIThe AllkRANN class is the all-k-rank-approximate-nearest-neighbors method\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Parikshit Ram
.RE
.PP
Simple typedefs describing template instantiations of the \fBRASearch\fP class which are commonly used\&.
.PP
This file is part of mlpack 1\&.0\&.12\&.
.PP
mlpack is free software; you may redstribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBra_typedef\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
